Support of external members
eProsima/Fast-CDR pull request #170
Opened 2023-10-10 09:58 UTC by richiware

2023-10-10 11:09 UTC, richiprosima commented
Build status:
* Linux [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastCDR%20Manual%20Linux&build=315)](http://jenkins.eprosima.com:8080/job/FastCDR%20Manual%20Linux/315/)
* Mac [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastCDR%20Manual%20Mac&build=229)](http://jenkins.eprosima.com:8080/job/FastCDR%20Manual%20Mac/229/)
* Windows [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastCDR%20Manual%20Windows&build=314)](http://jenkins.eprosima.com:8080/job/FastCDR%20Manual%20Windows/314/)

2023-10-17 10:51 UTC, JLBuenoLopez-eProsima commented
[Manual CI run](http://jenkins.eprosima.com:8080/job/FastCDR%20Manual/314/): SUCCESS

2023-10-17 13:07 UTC, JLBuenoLopez-eProsima requested changes
A few typos in the comments. Implementation LGTM!

2023-10-24 10:02 UTC, richiware commented on test/xcdr/external.cpp
> +        //{ Encode optional not present.
Done in 0f9a604

2023-10-24 10:02 UTC, richiware commented on test/xcdr/external.cpp
> +    //{ Encode optional not present.
Done in 0f9a604

2023-10-24 10:02 UTC, richiware commented on test/xcdr/external.cpp
> +//! @test Tests the deference object functions.
Done in 0f9a604

2023-10-24 10:02 UTC, richiware commented on test/xcdr/external.cpp
> +    // Calling assignment over an empty external with an locked external;
Done in 0f9a604

2023-10-24 10:02 UTC, richiware commented on include/fastcdr/xcdr/external.hpp
> +    //! Deference object member.
Done in 0f9a604

2023-10-24 10:02 UTC, richiware commented on include/fastcdr/xcdr/external.hpp
> +    //! Deference object.
Done in 0f9a604

2023-10-24 11:51 UTC, richiprosima commented
Build status:
* Linux [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastCDR%20Manual%20Linux&build=323)](http://jenkins.eprosima.com:8080/job/FastCDR%20Manual%20Linux/323/)
* Mac [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastCDR%20Manual%20Mac&build=236)](http://jenkins.eprosima.com:8080/job/FastCDR%20Manual%20Mac/236/)
* Windows [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastCDR%20Manual%20Windows&build=322)](http://jenkins.eprosima.com:8080/job/FastCDR%20Manual%20Windows/322/)

2023-10-24 12:03 UTC, richiware commented
Relaunched Mac job success: [link](http://jenkins.eprosima.com:8080/job/FastCDR%20Manual%20Mac/237/)

2023-10-24 12:19 UTC, JLBuenoLopez-eProsima approved these changes
LGTM

2023-10-24 12:20 UTC, merged