Fix warning on VS2017
eProsima/Fast-CDR pull request #176
Opened 2023-11-10 10:13 UTC by richiware

2023-11-10 10:23 UTC, richiprosima commented
Build status:
* Linux [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastCDR%20Manual%20Linux&build=325)](http://jenkins.eprosima.com:8080/job/FastCDR%20Manual%20Linux/325/)
* Mac [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastCDR%20Manual%20Mac&build=239)](http://jenkins.eprosima.com:8080/job/FastCDR%20Manual%20Mac/239/)
* Windows [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastCDR%20Manual%20Windows&build=324)](http://jenkins.eprosima.com:8080/job/FastCDR%20Manual%20Windows/324/)

2023-11-12 05:52 UTC, richiprosima commented
Build status:
* Linux [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastCDR%20Manual%20Linux&build=326)](http://jenkins.eprosima.com:8080/job/FastCDR%20Manual%20Linux/326/)
* Mac [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastCDR%20Manual%20Mac&build=240)](http://jenkins.eprosima.com:8080/job/FastCDR%20Manual%20Mac/240/)
* Windows [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastCDR%20Manual%20Windows&build=325)](http://jenkins.eprosima.com:8080/job/FastCDR%20Manual%20Windows/325/)

2023-11-13 07:42 UTC, JLBuenoLopez-eProsima requested changes
Changes LGTM though there is one file whose changes need to be reverted. Let us wait for the CI results and as the changes does not affect the CI, we can proceed and merge.

2023-11-13 07:42 UTC, JLBuenoLopez-eProsima commented on fastcdr.repos
Please, revert changes in this file.

2023-11-13 13:18 UTC, richiprosima commented
Build status:
* Linux [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastCDR%20Manual%20Linux&build=327)](http://jenkins.eprosima.com:8080/job/FastCDR%20Manual%20Linux/327/)
* Mac [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastCDR%20Manual%20Mac&build=241)](http://jenkins.eprosima.com:8080/job/FastCDR%20Manual%20Mac/241/)
* Windows [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastCDR%20Manual%20Windows&build=326)](http://jenkins.eprosima.com:8080/job/FastCDR%20Manual%20Windows/326/)

2023-11-13 13:26 UTC, JLBuenoLopez-eProsima approved these changes

2023-11-13 13:27 UTC, merged

2023-11-13 19:40 UTC, richiprosima commented
Build status:
* Linux [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastCDR%20Manual%20Linux&build=328)](http://jenkins.eprosima.com:8080/job/FastCDR%20Manual%20Linux/328/)
* Mac [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastCDR%20Manual%20Mac&build=242)](http://jenkins.eprosima.com:8080/job/FastCDR%20Manual%20Mac/242/)
* Windows [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastCDR%20Manual%20Windows&build=327)](http://jenkins.eprosima.com:8080/job/FastCDR%20Manual%20Windows/327/)