[20328] Add support for building tests within an ament context
eProsima/Fast-CDR pull request #200
Opened 2024-02-21 15:14 UTC by EduPonz

This PR adds support for building Fast CDR within an ament context (as is the ROS 2 CI).

Since Fast CDR v2.0.0, the CMake option to build the tests is the CMake standard `-DBUILD_TESTING=ON`. When trying to introduce Fast CDR v2 in ROS 2, ROS 2 CI was failing because that CI builds all packages with `-DBUILD_TESTING=ON`, and in that context Fast CDR could not find GTest because is not installed in the system.

In the ROS 2 ecosystem, there are vendor packages within ament for GTest, which are the ones the CI is using. However, Fast CDR's CMakeLists.txt was doing a plain `find_package(GTest REQUIRED)`, and thus failing. In order to find GTest in that context, ament's infrastructure needs to be used. This PR:

1. Adds a package.xml to Fast CDR for ROS 2 packaging. This means that when Fast CDR v2.2.0 in included in ROS 2 Rolling, we could dispose of [this patch file](https://github.com/ros2-gbp/fastcdr-release/blob/master/rolling/package.xml).
2. Extends the existing colcon.pkg to included the ament dependencies so the build order is correctly set by colcon. We cannot simply dispose of this file, as then colcon does not build GTest before Fast CDR when building tests.
3. Adds a CMake macro `find_or_add_gtest` to correctly include GTest both in and outside an ament context.
4. Forces C++14 when building tests, as in at the moment ROS 2 Rolling uses GTest 1.14, which requires it, and our CI system supports it. For building the library, C++11 is still the minimum required and is still enforced by default.

2024-02-21 20:33 UTC, richiprosima commented
Build status:
* Linux [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastCDR%20Manual%20Linux&build=387)](http://jenkins.eprosima.com:8080/job/FastCDR%20Manual%20Linux/387/)
* Mac [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastCDR%20Manual%20Mac&build=288)](http://jenkins.eprosima.com:8080/job/FastCDR%20Manual%20Mac/288/)
* Windows [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastCDR%20Manual%20Windows&build=368)](http://jenkins.eprosima.com:8080/job/FastCDR%20Manual%20Windows/368/)

2024-02-22 06:51 UTC, richiware requested changes

2024-02-22 06:51 UTC, richiware commented on test/CMakeLists.txt
> +include(${PROJECT_SOURCE_DIR}/cmake/common/check_configuration.cmake)
Duplicated. Already loaded in root CMakeLists.txt file.

2024-02-22 14:11 UTC, richiware approved these changes

2024-02-22 17:35 UTC, merged