[20414] Add PR template
eProsima/Fast-CDR pull request #203
Opened 2024-02-26 08:41 UTC by JesusPoderoso

## Description

This PR adds this PR template

## Contributor Checklist
- [x] Commit messages follow the project guidelines. 
- **N/A** Any new/modified methods have been properly documented using Doxygen. 
- **N/A** Tests pass locally.
- **N/A** Applicable backports have been included in the description.

## Reviewer Checklist
- [x] The PR has a milestone assigned.
- [ ] The title and description correctly express the PR's purpose.
- [ ] Check contributor checklist is correct.
- [ ] Check CI results: changes do not issue any warning.

2024-05-14 05:41 UTC, EduPonz requested changes

2024-05-14 05:41 UTC, EduPonz commented on .github/pull_request_template.md
> +- [ ] Applicable backports have been included in the description.
I think API and ABI compatibility and also quite important here. I'd also include the cross emoji that we have on Fast DDS. In fact, this list could be almost the same as the one in Fast DDS

2024-05-14 05:41 UTC, EduPonz commented on .github/pull_request_template.md
> +- [ ] The PR has a milestone assigned.
```suggestion
## Reviewer Checklist

- [ ] The PR has a milestone assigned.
```

2024-05-14 05:41 UTC, EduPonz commented on .github/pull_request_template.md
> +- [ ] Check CI results: changes do not issue any warning.
I think CI should pass as well

2024-05-14 07:10 UTC, richiprosima commented
Build status:
* Linux [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastCDR%20Manual%20Linux&build=397)](http://jenkins.eprosima.com:8080/job/FastCDR%20Manual%20Linux/397/)
* Mac [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastCDR%20Manual%20Mac&build=296)](http://jenkins.eprosima.com:8080/job/FastCDR%20Manual%20Mac/296/)
* Windows [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastCDR%20Manual%20Windows&build=378)](http://jenkins.eprosima.com:8080/job/FastCDR%20Manual%20Windows/378/)

2024-05-14 07:14 UTC, EduPonz requested changes

2024-05-14 07:14 UTC, EduPonz commented on .github/pull_request_template.md
> +- [ ] The code follows the style guidelines of this project. <!-- Please refer to the [Quality Declaration](https://github.com/eProsima/Fast-DDS/blob/master/QUALITY.md#linters-and-static-analysis-4v)
Incorrect link in commit

2024-05-14 08:46 UTC, richiprosima commented
Build status:
* Linux [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastCDR%20Manual%20Linux&build=398)](http://jenkins.eprosima.com:8080/job/FastCDR%20Manual%20Linux/398/)
* Mac [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastCDR%20Manual%20Mac&build=297)](http://jenkins.eprosima.com:8080/job/FastCDR%20Manual%20Mac/297/)
* Windows [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastCDR%20Manual%20Windows&build=379)](http://jenkins.eprosima.com:8080/job/FastCDR%20Manual%20Windows/379/)

2024-07-09 08:27 UTC, EduPonz approved these changes

2024-07-09 08:28 UTC, merged

2024-07-09 08:29 UTC, richiprosima commented
Build status:
* Linux [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastCDR%20Manual%20Linux&build=404)](http://jenkins.eprosima.com:8080/job/FastCDR%20Manual%20Linux/404/)
* Mac ![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?status=not%20run&color=bbb)
* Windows [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastCDR%20Manual%20Windows&build=386)](http://jenkins.eprosima.com:8080/job/FastCDR%20Manual%20Windows/386/)