Fix a compile warning with g++ 13.2.0.
eProsima/Fast-CDR pull request #207
Opened 2024-03-28 15:35 UTC by clalancette

When building the tests with g++ 13.2.0, it complains that the EXPECT_LONG_DOUBLE_EQ macro has no effect. That ends up being true; because it is just a x == y, with no EXPECT statement around it, it actually does nothing.

Here, I just remove this macro because it is unnecessary; we can just do EXPECT_TRUE(x == y) and get the same effect with less code.

This is targeted at the 2.2.x branch because that is what we are using in ROS 2, but this applies equally to the master branch.

2024-03-28 18:16 UTC, MiguelCompany requested changes
I think it would be better to correctly define `EXPECT_LONG_DOUBLE_EQ` as a `EXPECT_TRUE(x == y)`

2024-03-29 10:43 UTC, MiguelCompany commented
@clalancette I reverted your commit here, and followed a different approach.

I recall there was a reason for doing things different with long double types. There might be precission issues on some platforms / compilers when serializing a long double and deserializing it back. Having a specific implementation for checking equality of two values allows changing the implementation if necessary.

So I just changed `EXPECT_LONG_DOUBLE_EQ` to be a function instead of a macro, and implemented it as `EXPECT_TRUE(val1 == val2)`. The tests are passing, so I am approving and merging this

2024-03-29 10:44 UTC, MiguelCompany commented
One mor thing. I change the base to `master` since we have a mirror workflow from `master` into `2.2.x`

2024-03-29 10:45 UTC, merged

2024-03-29 12:17 UTC, clalancette commented
> One mor thing. I change the base to `master` since we have a mirror workflow from `master` into `2.2.x`

Fantastic, this looks great.  Thanks.