Fix: function definition is marked dllimport
eProsima/Fast-CDR pull request #210
Opened 2024-06-04 01:49 UTC by felixf4xu

Fix #209

2024-06-06 06:16 UTC, JesusPoderoso approved these changes
LGTM!
Thanks for your contribution @felixf4xu! 🚀

2024-06-06 06:21 UTC, JesusPoderoso requested changes
Just a nitpick to pass our linter

2024-06-06 06:21 UTC, JesusPoderoso commented on src/cpp/Cdr.cpp
> +
```suggestion
```

2024-06-06 06:21 UTC, JesusPoderoso commented on src/cpp/Cdr.cpp
> +
```suggestion
```

2024-06-06 14:19 UTC, JesusPoderoso approved these changes

2024-06-06 14:28 UTC, felixf4xu commented
Thanks for the review.

At the same time, I have a question about the compiling switches. The issue only happens when fastcdr is built as a shared dll (on Windows), in ros2, it's `BUILD_SHARED_LIBS`. I'm just curious, this project has all code ready (the difinition of `Cdr_DllAPI` and all the other stuff) but this issue show that maybe it's never compiled on Windows as shared dll.

ROS2 actually supports Windows, maybe it's build as a static lib on Windows?

The reason why I asked is that I actually have begun to work on fastrtps as well, it has even more issues like this one, but again, fastrtsp seems to be ready for windows shared dll because it already has all the code there, just not tested, maybe nobody wants to build it on Windows as shared dll?

2024-06-06 14:37 UTC, felixf4xu commented
And I see the github actions for this fastcdr project, Windows is also listed there. I'm curious if it's configured to compile as static lib?

I'm not familiar with github actions, is it possible to set some actions to build on windows as shared dll?

2024-06-06 15:08 UTC, MiguelCompany commented
@felixf4xu It might be something related with the compiler.

As stated in the supported platforms [here](https://fast-dds.docs.eprosima.com/en/stable/notes/versions.html#build-system-dependencies), our tier 1 build system on Windows is Visual Studio 2019.

On that tier 1 platform we pass the CI with `BUILD_SHARED_LIBS=ON`, so the DLL system is always tested.

The error you mention in #209 is usually reported by MinGW. If you are building in MinGW then bear in mind that it is not an officially supported platform.

2024-06-10 06:46 UTC, richiprosima commented
Build status:
* Linux [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastCDR%20Manual%20Linux&build=400)](http://jenkins.eprosima.com:8080/job/FastCDR%20Manual%20Linux/400/)
* Mac ![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?status=not%20run&color=bbb)
* Windows [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastCDR%20Manual%20Windows&build=381)](http://jenkins.eprosima.com:8080/job/FastCDR%20Manual%20Windows/381/)

2024-06-10 06:46 UTC, richiprosima commented
Build status:
* Linux [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastCDR%20Manual%20Linux&build=400)](http://jenkins.eprosima.com:8080/job/FastCDR%20Manual%20Linux/400/)
* Mac ![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?status=not%20run&color=bbb)
* Windows [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastCDR%20Manual%20Windows&build=382)](http://jenkins.eprosima.com:8080/job/FastCDR%20Manual%20Windows/382/)

2024-10-01 13:30 UTC, MiguelCompany commented
@mergifyio rebase

2024-11-11 07:10 UTC, MiguelCompany commented
CI:
* [Windows](https://github.com/eProsima/Fast-CDR/actions/runs/11773794535)
* [Ubuntu](https://github.com/eProsima/Fast-CDR/actions/runs/11773796344)
* [Mac](https://github.com/eProsima/Fast-CDR/actions/runs/11773797644)

2024-11-11 14:17 UTC, MiguelCompany commented
CI run successfully on #247

2024-11-11 14:17 UTC, merged