[21286] Improve CI workflows in master
eProsima/Fast-CDR pull request #213
Opened 2024-07-01 11:10 UTC by JesusPoderoso

## Description

This PR improves the CI workflows, making them as similar as possible to the Fast DDS workflows.
It also introduces a braching model refactor, similiar as the performed in Fast DDS repository.

It is on top of (and must be merged after) this PR:
- #203 

**Note**: While backporting this PR, please ensure the following changes:
- Remove nightly jobs
- Update `ubuntu-ci.yml`, `mac-ci.yml` and `windows-ci.yml` files with the proper fallback branches
- Fast CDR 1.0.x requires building on `ubuntu-20.04`

@Mergifyio backport 2.2.x 2.1.x 1.1.x 1.0.x 

## Contributor Checklist

- [x] Commit messages follow the project guidelines. 
- **N/A** The code follows the style guidelines of this project. 
- **N/A** Tests that thoroughly check the new feature have been added/Regression tests checking the bug and its fix have been added; the added tests pass locally 
- **N/A** Any new/modified methods have been properly documented using Doxygen. 
- **N/A** Changes are backport compatible: they do **NOT** break ABI nor change library core behavior. 
- **N/A** Changes are API compatible. 
- **N/A** New feature has been added to the `versions.md` file (if applicable).
- [x] Applicable backports have been included in the description.

## Reviewer Checklist

- [ ] The PR has a milestone assigned.
- [ ] The title and description correctly express the PR's purpose.
- [ ] Check contributor checklist is correct.
- [ ] Check CI results: changes do not issue any warning.
- [ ] Check CI results: CI pass and failing tests are unrelated with the changes.

2024-07-01 11:10 UTC, JesusPoderoso commented
Note: I am not sure if the correct milestone should be v3.0.0 or v2.3.0

2024-07-08 13:45 UTC, richiprosima commented
Build status:
* Linux [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastCDR%20Manual%20Linux&build=403)](http://jenkins.eprosima.com:8080/job/FastCDR%20Manual%20Linux/403/)
* Mac ![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?status=not%20run&color=bbb)
* Windows [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastCDR%20Manual%20Windows&build=385)](http://jenkins.eprosima.com:8080/job/FastCDR%20Manual%20Windows/385/)

2024-07-09 09:07 UTC, EduPonz requested changes

2024-07-09 09:07 UTC, EduPonz commented on .github/workflows/reusable-ubuntu-ci.yml
I think we can make do with only one "multiplatform" reusable. The only thing missing is the toolset, but I think we could have it as an opt-in arg that only takes effect on windows

2024-07-09 09:07 UTC, EduPonz commented on RELEASE_SUPPORT.md
> +Please, refer to the [main branch](https://github.com/eProsima/Fast-CDR/blob/master/RELEASE_SUPPORT.md) for the latest version of this document.
```suggestion
Please, refer to the [master branch](https://github.com/eProsima/Fast-CDR/blob/master/RELEASE_SUPPORT.md) for the latest version of this document.
```

2024-07-09 09:07 UTC, EduPonz commented on RELEASE_SUPPORT.md
> +|Fast DDS Version|Fast DDS Python Version|Fast DDS Python Version branch|Fast DDS Python Latest Release|
```suggestion
|Fast DDS Version|Fast CDR Version|Fast CDR Version branch|Fast CDR Latest Release|
```

2024-07-09 09:36 UTC, richiprosima commented
Build status:
* Linux [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastCDR%20Manual%20Linux&build=405)](http://jenkins.eprosima.com:8080/job/FastCDR%20Manual%20Linux/405/)
* Mac ![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?status=not%20run&color=bbb)
* Windows [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastCDR%20Manual%20Windows&build=387)](http://jenkins.eprosima.com:8080/job/FastCDR%20Manual%20Windows/387/)

2024-07-09 11:21 UTC, richiprosima commented
Build status:
* Linux [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastCDR%20Manual%20Linux&build=406)](http://jenkins.eprosima.com:8080/job/FastCDR%20Manual%20Linux/406/)
* Mac ![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?status=not%20run&color=bbb)
* Windows [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastCDR%20Manual%20Windows&build=388)](http://jenkins.eprosima.com:8080/job/FastCDR%20Manual%20Windows/388/)

2024-07-10 06:59 UTC, richiprosima commented
Build status:
* Linux [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastCDR%20Manual%20Linux&build=407)](http://jenkins.eprosima.com:8080/job/FastCDR%20Manual%20Linux/407/)
* Mac ![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?status=not%20run&color=bbb)
* Windows [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastCDR%20Manual%20Windows&build=389)](http://jenkins.eprosima.com:8080/job/FastCDR%20Manual%20Windows/389/)

2024-07-11 10:15 UTC, closed without merging

2024-07-11 10:17 UTC, JesusPoderoso commented
Closed in favor of:
- https://github.com/eProsima/Fast-CDR/pull/216

2024-07-11 11:22 UTC, richiprosima commented
Build status:
* Linux [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastCDR%20Manual%20Linux&build=410)](http://jenkins.eprosima.com:8080/job/FastCDR%20Manual%20Linux/410/)
* Mac ![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?status=not%20run&color=bbb)
* Windows [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastCDR%20Manual%20Windows&build=392)](http://jenkins.eprosima.com:8080/job/FastCDR%20Manual%20Windows/392/)