Add Quality Declaration
eProsima/Fast-CDR pull request #85
Opened 2020-09-22 13:42 UTC by JLBuenoLopez-eProsima

Add Fast CDR Quality Declaration
Update README to link to the Quality Declaration

For more info about the code style, please refer to eProsima/cpp-style#3

For more info about CONTRIBUTING, please refer to eProsima/policies#2

For more info about the Fast-CDR documentation (API reference), please refer to eProsima/all-docs#17

2020-09-22 14:53 UTC, richiware commented
Build status:
* Linux [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastCDR%20Manual%20Linux&build=45)](http://jenkins.eprosima.com:8080/job/FastCDR%20Manual%20Linux/45/)
* Windows [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastCDR%20Manual%20Windows&build=46)](http://jenkins.eprosima.com:8080/job/FastCDR%20Manual%20Windows/46/)

2020-09-23 13:22 UTC, richiware commented
Build status:
* Linux [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastCDR%20Manual%20Linux&build=48)](http://jenkins.eprosima.com:8080/job/FastCDR%20Manual%20Linux/48/)
* Windows [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastCDR%20Manual%20Windows&build=49)](http://jenkins.eprosima.com:8080/job/FastCDR%20Manual%20Windows/49/)

2020-09-23 13:22 UTC, richiware commented
Build status:
* Linux [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastCDR%20Manual%20Linux&build=48)](http://jenkins.eprosima.com:8080/job/FastCDR%20Manual%20Linux/48/)
* Linux aarch64[![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastCDR%20Manual%20Linux%20aarch64&build=3)](http://jenkins.eprosima.com:8080/job/FastCDR%20Manual%20Linux%20aarch64/3/)
* Mac [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastCDR%20Manual%20Mac&build=3)](http://jenkins.eprosima.com:8080/job/FastCDR%20Manual%20Mac/3/)
* Windows [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastCDR%20Manual%20Windows&build=49)](http://jenkins.eprosima.com:8080/job/FastCDR%20Manual%20Windows/49/)

2020-09-23 20:57 UTC, brawner approved these changes
Looks good!

2020-09-25 11:54 UTC, MiguelCompany requested changes

2020-09-25 11:54 UTC, MiguelCompany commented on QUALITY.md
> +*eprosima Fast DDS* vulnerability Disclosure Policy can be found [here](https://github.com/eProsima/policies/blob/main/VULNERABILITY.md)
```suggestion
**eprosima Fast CDR** vulnerability Disclosure Policy can be found [here](https://github.com/eProsima/policies/blob/main/VULNERABILITY.md)
```

2020-09-25 11:54 UTC, MiguelCompany commented on QUALITY.md
> +The chart below compares the requirements in the [REP-2004](https://www.ros.org/reps/rep-2004.html#quality-level-comparison-chart) with the current state of *eprosima Fast DDS*
```suggestion
The chart below compares the requirements in the [REP-2004](https://www.ros.org/reps/rep-2004.html#quality-level-comparison-chart) with the current state of **eprosima Fast CDR**
```

2020-09-28 05:24 UTC, MiguelCompany approved these changes

2020-09-28 06:51 UTC, merged